-- ============================================
-- Identity Service Database Schema (Simplified)
-- UTH-ConfMS - Identity & Authentication
-- ============================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(500) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    affiliation VARCHAR(255),
    department VARCHAR(255),
    title VARCHAR(100),
    country VARCHAR(100),
    phone VARCHAR(20),
    orcid VARCHAR(50),
    google_scholar_id VARCHAR(100),
    bio TEXT,
    profile_picture_url VARCHAR(500),
    password_reset_token VARCHAR(255),
    password_reset_expires TIMESTAMP,
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(45),
    login_count INT DEFAULT 0,
    failed_login_attempts INT DEFAULT 0,
    account_locked_until TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);

-- ============================================
-- ROLES TABLE
-- ============================================
CREATE TABLE roles (
    role_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role_name VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    description TEXT,
    is_system_role BOOLEAN DEFAULT FALSE,
    role_level VARCHAR(50) DEFAULT 'CONFERENCE',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO roles (role_name, display_name, description, is_system_role, role_level) VALUES
('SYSTEM_ADMIN', 'System Administrator', 'Full system access', TRUE, 'SYSTEM'),
('CONFERENCE_CHAIR', 'Conference Chair', 'Conference organizer', FALSE, 'CONFERENCE'),
('REVIEWER', 'Reviewer', 'Paper reviewer', FALSE, 'CONFERENCE'),
('AUTHOR', 'Author', 'Paper author', FALSE, 'CONFERENCE');

-- ============================================
-- USER_ROLES TABLE
-- ============================================
CREATE TABLE user_roles (
    user_role_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    conference_id UUID,
    track_id UUID,
    is_active BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMP,
    assigned_by UUID,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, role_id, conference_id)
);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);
CREATE INDEX idx_user_roles_conference_id ON user_roles(conference_id);

-- ============================================
-- REFRESH_TOKENS TABLE
-- ============================================
CREATE TABLE refresh_tokens (
    token_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP,
    revoked_by_ip VARCHAR(45),
    replaced_by_token VARCHAR(500),
    created_by_ip VARCHAR(45)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);

-- ============================================
-- AUDIT_LOGS TABLE
-- ============================================
CREATE TABLE audit_logs (
    log_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(user_id),
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100),
    resource_id UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);

-- ============================================
-- TRIGGERS
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_roles_updated_at BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- SEED TEST USERS
-- BCrypt hashes generated by pgcrypto (compatible with .NET BCrypt)
-- ============================================
-- | Role             | Email                | Password        |
-- |------------------|----------------------|-----------------|
-- | System Admin     | admin@uth.edu.vn     | Admin@123456    |
-- | Conference Chair | chair@uth.edu.vn     | Chair@123456    |
-- | Reviewer         | reviewer@uth.edu.vn  | Reviewer@123456 |
-- | Author           | author@uth.edu.vn    | Author@123456   |
-- ============================================

INSERT INTO users (email, username, password_hash, full_name, affiliation, is_active) VALUES
('admin@uth.edu.vn', 'admin', crypt('Admin@123456', gen_salt('bf', 11)), 'System Administrator', 'UTH', TRUE),
('chair@uth.edu.vn', 'chair', crypt('Chair@123456', gen_salt('bf', 11)), 'Conference Chair', 'UTH', TRUE),
('reviewer@uth.edu.vn', 'reviewer', crypt('Reviewer@123456', gen_salt('bf', 11)), 'Test Reviewer', 'UTH', TRUE),
('author@uth.edu.vn', 'author', crypt('Author@123456', gen_salt('bf', 11)), 'Test Author', 'UTH', TRUE);

-- Assign roles to users
INSERT INTO user_roles (user_id, role_id, is_active)
SELECT u.user_id, r.role_id, TRUE
FROM users u, roles r
WHERE u.email = 'admin@uth.edu.vn' AND r.role_name = 'SYSTEM_ADMIN';

INSERT INTO user_roles (user_id, role_id, is_active)
SELECT u.user_id, r.role_id, TRUE
FROM users u, roles r
WHERE u.email = 'chair@uth.edu.vn' AND r.role_name = 'CONFERENCE_CHAIR';

INSERT INTO user_roles (user_id, role_id, is_active)
SELECT u.user_id, r.role_id, TRUE
FROM users u, roles r
WHERE u.email = 'reviewer@uth.edu.vn' AND r.role_name = 'REVIEWER';

INSERT INTO user_roles (user_id, role_id, is_active)
SELECT u.user_id, r.role_id, TRUE
FROM users u, roles r
WHERE u.email = 'author@uth.edu.vn' AND r.role_name = 'AUTHOR';
